config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "oauths/callback"
  get "my_posts/index"
  root "static_pages#top"

  get "terms", to: "pages#terms"
  get "privacy_policy", to: "pages#privacy_policy"

  get "sign_up", to: "users#new"
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: [ :new, :create ]

  resources :my_posts, only: [ :index ]
  resources :my_likes, only: [ :index ]

  resources :posts do
    resources :likes, only: [ :create, :destroy ]
  end
end

app/controllers/my_posts_controller.rb
class MyPostsController < ApplicationController
  before_action :require_login

  def index
    @post = Post.new
    @posts = current_user.posts.eager_load(:likes).order(created_at: :desc)
    @likes_by_post = Like.where(post_id: @posts.map(&:id)).group_by(&:post_id)
    @message = @posts.empty? ? "あなたの投稿はありません" : nil
  end
end

app/helpers/my_posts_helper.rb
module MyPostsHelper
end

app/views/my_posts/_post.html.erb
<!--- 自分の投稿のデザイン --->
<div class="w-96 p-4 border border-white/50 rounded-xl bg-white/60 backdrop-blur-md shadow-md">
  <div class="card-body">
    <div class="ml-auto">
      <% if post.published? %>
        <span class="public-mark text-green-500"><i class="fa-solid fa-lock-open"></i></span>
      <% else %>
        <span class="private-mark text-red-500"><i class="fa-solid fa-lock"></i></span>
      <% end %>
    </div>
    <p class="text-black text-lg"><%= post.content %></p>
    <p class="text-gray-500 text-sm mb-0.5"><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></p>
    <div class="mb-0">
      <%= render 'posts/like_buttons', post: post, likes: @likes_by_post[post.id] %>
    </div>
    <div class="flex justify-end space-x-2 mt-1">
      <button onclick="document.getElementById('edit_modal_<%= post.id %>').showModal()" class="text-gray-700 hover:text-blue-500 transition">
        <i class="fa-solid fa-pen-fancy text-lg"></i>
      </button>

      <%= link_to post_path(post), id: "button-delete-#{post.id}", data: { turbo_method: :delete }, class: 'text-gray-700 hover:text-red-500 transition' do %>
        <i class="fa-solid fa-trash-can text-lg"></i>
      <% end %>
    </div>
  </div>
</div>

<!--- 編集モーダル --->
<dialog id="edit_modal_<%= post.id %>" class="modal">
  <div class="modal-box bg-white">
    <h3 class="text-lg font-bold text-black">投稿を編集</h3>
    <%= form_with model: post, url: post_path(post), method: :patch, local: true do |f| %>
      <div class="form-grouptext-white">
        <%= f.text_area :content, class: "form-control w-full", rows: 5 %>
      </div>
      <div class="form-group text-white">
        <%= f.label :status, "ステータス" %>
        <%= f.select :status, [['公開', 'published'], ['非公開', 'unpublished']], {}, class: "form-control" %>
      </div>
      <div class="modal-action">
        <%= f.submit "更新", class: "btn btn-primary" %>
        <button type="button" onclick="document.getElementById('edit_modal_<%= post.id %>').close()" class="btn red">キャンセル</button>
      </div>
    <% end %>
  </div>
</dialog>

app/views/my_posts/index.html.erb
<div class="relative w-full min-h-screen flex flex-col items-center py-16 bg-cover bg-center">
  <h2 class="text-center text-lg font-sans"><%= current_user.username %>さんの投稿一覧</h2>

<!-- 投稿用のモーダル -->
<button class="btn btn-primary" onclick="my_modal_1.showModal()">投稿作成</button>
<dialog id="my_modal_1" class="modal">
  <div class="modal-box bg-white">
    <h3 class="text-lg font-bold text-black">投稿作成画面</h3>
    <%= form_with model: @post, url: posts_path, method: :post, local: true do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: "form-control w-full", placeholder: "投稿内容", rows: 5 %>
      </div>
      <div class="form-group">
        <%= f.label :status, "ステータス" %>
        <%= f.select :status, [['公開', 'published'], ['非公開', 'unpublished']], { prompt: '選択してください' }, class: "form-control text-white" %>
      </div>
      <div class="form-group">
        <%= f.submit "作成", class: "btn btn-primary" %>
      </div>
    <% end %>
    <div class="modal-action">
      <form method="dialog">
        <button class="btn btn-error">閉じる</button>
      </form>
    </div>
  </div>
</dialog>

<!--- ページ用のタブ --->
  <div class="flex justify-center">
    <div role="tablist" class="tabs tabs-bordered w-96 gap-2">
      <div role="tab" class="tab flex-1 text-center">
        <%= link_to 'みんなの投稿', posts_path %>
      </div>
      <div role="tab" class="tab flex-1 text-center">
        <%= link_to '自分の投稿', my_posts_path(current_user) %>
      </div>
      <div role="tab" class="tab flex-1 text-center">
        <%= link_to '共感一覧', my_likes_path(current_user) %>
      </div>
    </div>
  </div>

<!--- 自分の投稿を表示 --->
  <div class="flex justify-center">
    <div class="max-w-2xl w-full">
      <% @posts.each do |post| %>
        <%= render 'my_posts/post', post: post, likes: @likes_by_post[post.id] %>
      <% end %>
    </div>
  </div>
</div>