config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "oauths/callback"
  get "my_posts/index"
  root "static_pages#top"

  get "terms", to: "pages#terms"
  get "privacy_policy", to: "pages#privacy_policy"

  get "sign_up", to: "users#new"
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: [ :new, :create ]

  resources :my_posts, only: [ :index ]
  resources :my_likes, only: [ :index ]

  resources :posts do
    resources :likes, only: [ :create, :destroy ]
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :posts

  validates :password, length: {minimum: 8, message: "は8文字以上である必要があります"}, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: {message: "が一致しません"}, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: {message: "を入力してください"}, if: -> { new_record? || changes[:crypted_password] }
  validates :username, presence: {message: "を入力してください"}, length: {maximum: 10, message: "は10文字以内である必要があります"}
  validates :email, presence: {message: "を入力してください"}, uniqueness: {message: "：このメールアドレスは登録済みです"}
  validates :terms_accepted, acceptance: {accept: true, message: "に同意する必要があります"}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to posts_path, notice: "ユーザーが作成されました"
    else
      flash.now[:alert] = "ユーザー登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="relative w-full min-h-screen flex flex-col justify-center items-center py-24 bg-cover bg-center">
  <h1 class="text-2xl font-bold text-sans text-white/50 mb-8">ユーザー登録</h1>

  <%= form_with(model: @user, local: true, class: "w-80 md:w-96 bg-white/10 p-6 rounded-xl shadow-lg backdrop-blur-md") do |f| %>
    <div class="mb-4 md:mb-6">
      <%= f.label :username, class: "block text-serif text-white/70 mb-2" %>
      <%= f.text_field :username, class: "w-full p-3 rounded-lg bg-white/20 text-white focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-4 md:mb-6">
      <%= f.label :email, class: "block text-serif text-white/70 mb-2" %>
      <%= f.email_field :email, class: "w-full p-3 rounded-lg bg-white/20 text-white focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-4 md:mb-6">
      <%= f.label :password, class: "block text-serif text-white/70 mb-2" %>
      <%= f.password_field :password, class: "w-full p-3 rounded-lg bg-white/20 text-white focus:outline-none focus:ring-2 focus:ring-blue-500", placeholder:'パスワードは8文字以上で作成してください' %>
    </div>

    <div class="mb-4 md:mb-6">
      <%= f.label :password_confirmation, class: "block text-serif text-white/70 mb-2" %>
      <%= f.password_field :password_confirmation, class: "w-full p-3 rounded-lg bg-white/20 text-white focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-6">
      <%= f.submit "登録", class: "w-full py-3 bg-blue-500 text-serif text-white rounded-lg hover:bg-blue-600 transition duration-300" %>
    </div>

    <div class="flex items-center w-full my-4">
      <div class="flex-grow border-t border-white/50"></div>
      <span class="mx-4 text-serif text-white/50">または</span>
      <div class="flex-grow border-t border-white/50"></div>
    </div>

    <div class="flex justify-center">
      <%= link_to auth_at_provider_path(provider: :google) do %>
        <%= image_tag "google_sign_up.png", class: "w-48" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p><%= current_user.username %>さんの投稿一覧</p>

<br>
<h2 class="inline-block text-lg text-indigo-300">自分の投稿</h2>
<% @posts.each do |post| %>
  <div class="post">
    <div class="card bg-violet-50 w-96 border border-gray-300">
      <div class="card-body">
        <p class="text-black text-lg"><%= post.content %></p>
      </div>
      <%= link_to '編集', edit_post_path(post), id: "post_#{post.id}", class: 'btn btn-active btn-ghost' %>
      <%= link_to '削除', post_path(post), id: "button-delete-#{post.id}", data: { turbo_method: :delete }, class: 'btn btn-active btn-ghost' %>
    </div>
  </div>
<% end %>
</br>


<!-- 投稿用のモーダル -->
<button class="btn" onclick="my_modal_1.showModal()">投稿作成</button>
<dialog id="my_modal_1" class="modal">
  <div class="modal-box">
    <h3 class="text-lg font-bold">投稿作成画面</h3>
    <%= form_with model: @post, url: posts_path, method: :post, local: true do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: "form-control", placeholder: "ポスト内容", rows: 5 %>
      </div>
      <div class="form-group">
        <%= f.label :status, "ステータス" %>
        <%= f.select :status, [['公開', 'published'], ['非公開', 'unpublished']], { prompt: '選択してください' }, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "作成", class: "btn" %>
      </div>
    <% end %>
    <div class="modal-action">
      <form method="dialog">
        <button class="btn">Close</button>
      </form>
    </div>
  </div>
</dialog>