config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "oauths/callback"
  get "my_posts/index"
  root "static_pages#top"

  get "terms", to: "pages#terms"
  get "privacy_policy", to: "pages#privacy_policy"

  get "sign_up", to: "users#new"
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: [ :new, :create ]

  resources :my_posts, only: [ :index ]
  resources :my_likes, only: [ :index ]

  resources :posts do
    resources :likes, only: [ :create, :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :like_type, presence: true

  def self.group_by_post
    all.group_by(&:post_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :content, invalid_words: true
  validates :content, presence: true, length: {maximum: 140}

  enum status: {published: 0, unpublished: 1}, _default: :published # 投稿のステータス(公開・非公開)

  scope :published, -> { where(status: :published) } # 公開の投稿だけを取得

  def self.ransackable_attributes(auth_object = nil)
    ["content"]
  end

  # いいねしているかどうかの判断
  def liked_by?(user, like_type)
    likes.any? { |like| like.user_id == user.id && like.like_type == like_type }
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :posts

  validates :password, length: {minimum: 8, message: "は8文字以上である必要があります"}, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: {message: "が一致しません"}, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: {message: "を入力してください"}, if: -> { new_record? || changes[:crypted_password] }
  validates :username, presence: {message: "を入力してください"}, length: {maximum: 10, message: "は10文字以内である必要があります"}
  validates :email, presence: {message: "を入力してください"}, uniqueness: {message: "：このメールアドレスは登録済みです"}
  validates :terms_accepted, acceptance: {accept: true, message: "に同意する必要があります"}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_login
  before_action :update_like_data, only: [:create, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_or_initialize_by(post_id: @post.id, like_type: params[:like_type])

    if @like.persisted?
      @like.destroy
      Rails.logger.debug "Like successfully destroyed."
    else
      if @like.save
        Rails.logger.debug "Like saved successfully"
      else
        Rails.logger.error "Failed to save like"
        return head :unprocessable_entity
      end
    end

    update_like_data

    respond_to do |format|
      format.turbo_stream { render "likes/create" } # destroy の場合も create を使う
    end
  end


  def destroy
    @post = Post.find(params[:post_id])
    @like = @post.likes.find_by(like_type: params[:like_type], user: current_user)
    if @like
      @like.destroy
      Rails.logger.debug "Like successfully destroyed."
    else
      Rails.logger.warn "No like found to destroy."
    end

    # ここでデータを最新に更新
    update_like_data

    respond_to do |format|
      format.turbo_stream { render "likes/destroy" } # 明示的に `destroy.turbo_stream.erb` を指定
    end
  end

  private

  def update_like_data
    @user_likes = current_user.likes.group_by(&:post_id) # ユーザーのいいねデータを更新
    @likes_by_post = Like.group_by_post # 全体のいいねデータを更新
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_login, except: [ :terms, :privacy_policy ]

  def terms
    render "pages/terms"
  end

  def privacy_policy
    render "pages/privacy_policy"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  before_action :ensure_correct_user, only: [ :edit, :update, :destroy ]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).eager_load(:user, :likes).published.where.not(user_id: current_user.id).order(created_at: :desc)
    @likes_by_post = Like.where(post_id: @posts.map(&:id)).group_by(&:post_id) # 投稿ごとの全いいね数を事前に取得
    @user_likes = Like.where(user_id: current_user.id, post_id: @posts.map(&:id)).group_by(&:post_id) # ユーザーがいいねしたデータを事前取得
    @message = @posts.empty? ? "検索結果はありませんでした" : nil
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = @post.published? ? "公開で投稿されました！" : "非公開で投稿されました！"
      redirect_to my_posts_path
    else
      flash[:alert] = "投稿に失敗しました。"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = current_user.posts.find_by(id: params[:id])
    if @post.nil?
      redirect_to my_posts_path, alert: "投稿が見つかりませんでした"
    end
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      if @post.saved_change_to_content?
        flash[:notice] = "投稿を編集しました"
      elsif @post.saved_change_to_status?
        flash[:notice] = @post.published? ? "公開に変更されました" : "非公開に変更されました"
      else
        flash[:notice] = "変更はありませんでした"
      end
      redirect_to my_posts_path
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy
      redirect_to my_posts_path, notice: "投稿が削除されました", status: :see_other
    end
  end

  private

  # 不正アクセスを防ぐ
  def ensure_correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      flash[:alert] = "権限がありません、不正アクセスです！"
      redirect_to posts_path
    end
  end

  def post_params
    params.require(:post).permit(:content, :status, :id)# postパラメーターの中から必要な属性を許可する
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to posts_path, notice: "ユーザーが作成されました"
    else
      flash.now[:alert] = "ユーザー登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: "Empatia", # 自分のサイト名
      title: "自分の気持ちや感情を共有できるサービス",
      reverse: true,
      charset: "utf-8",
      description: "Empatiaでは、日々の思いや感情を投稿し、匿名だからこそ見つかる新しい共感のつながりを楽しむことができます。",
      keywords: "感情,気持ち,共感,共有",
      canonical: "https://www.app-empatia.com/",
      separator: "|",
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: "website",
        url: "https://www.app-empatia.com/",
        image: image_url("ogp.png"),
        local: "ja-JP"
      },
      twitter: {
        card: "summary_large_image",
        site: "@zhon3112", # 自分のアカウント
        image: image_url("ogp.png")
      }
    }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/my_likes_helper.rb
module MyLikesHelper
end

app/helpers/my_posts_helper.rb
module MyPostsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empatia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag('favicon.ico') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <!-- 背景色 -->
  <body class="relative bg-cover bg-center bg-fixed" style="background-image: url('<%= asset_path("top.jpg") %>');">
    <!-- オーバーレイ（全体を暗くする） -->
    <div class="absolute inset-0 bg-black bg-opacity-50 backdrop-blur-sm"></div>
    <!--- オーバーレイより前面にする --->
    <div class="relative z-10">
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_alert.html.erb
<div class="alert alert-<%= type %>">
  <%= message %>
</div>

app/views/shared/_app_explanation.html.erb
<!--- アプリの説明 --->
<div class="relative flex flex-col items-center justify-center w-full py-16 px-4">
  <!-- タイトル -->
  <h2 class="text-3xl md:text-4xl font-sans text-white/50 mb-8">Empatia</h2>

  <p class="text-lg md:text-xl text-serif text-white/50 max-w-3xl text-center leading-relaxed">
    Empatia は、「共感」を得たり他の人に「共感」を届けることができるアプリです。
  </p>

  <!-- カードレイアウト -->
  <div class="flex flex-col items-center gap-6 max-w-6xl w-full mt-10">
    <!-- カード -->
    <div class="border border-white/50 p-6 rounded-2xl shadow-lg backdrop-blur-md bg-white/10 w-full max-w-4xl">
      <h3 class="text-xl md:text-2xl font-sans text-white/50">何ができるの？</h3>
        <p class="text-base md:text-lg text-serif text-white/50 mt-2 space-y-2">
          <span class="before:content-['・'] before:mr-1 block">ユーザー名やアイコンの表示がないので匿名で気持ちや考えを投稿できます。</span>
          <span class="before:content-['・'] before:mr-1 block">他のユーザーの投稿に異なる感情のいいねボタンで共感することができます。</span>
          <span class="before:content-['・'] before:mr-1 block">コメント機能がないので偏見や誹謗中傷の心配がありません。</span>
        </p>
    </div>

    <div class="border border-white/50 p-6 rounded-2xl shadow-lg backdrop-blur-md bg-white/10 w-full max-w-4xl">
      <h3 class="text-xl md:text-2xl font-sans text-white/50">Empatiaの使い方</h3>
      <p class="text-base md:text-lg text-serif text-white/50 mt-2">
        ① 登録<br>
        ② 投稿して自分の今の気持ちをシェア<br>
        ③ 共感した投稿の感情に合ったリアクションを送ろう
      </p>
    </div>
  </div>

  <p class="text-lg md:text-xl text-serif text-white/50 max-w-3xl text-center leading-relaxed mt-10">
    Empatiaは、ただ共感を届けるための場所。<br>
    あなたの気持ちに寄り添う、温かい空間を一緒に作りましょう。
  </p>
</div>

app/views/shared/_before_login_header.html.erb
<header>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

	<div class="container mx-auto flex justify-end items-center px-4">
		<div class="flex gap-4 md:gap-10 text-serif text-base md:text-lg lg:text-xl text-white/50">
      <%= link_to 'Sign up', sign_up_path, class: 'hover:underline' %>
			<%= link_to 'Login', login_path, class: 'hover:underline' %>
		</div>
	</div>
</header>

app/views/shared/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="flash-message bg-blue-400 text-white text-lg font-bold p-4 rounded-md shadow-md">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash-message bg-red-500 text-white text-lg font-bold p-4 rounded-md shadow-md">
    <%= flash[:alert] %>
  </div>
<% end %>

<% if @user&.errors&.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @post&.errors&.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container mx-auto flex flex-col items-center">
		<div class="flex flex-col md:flex-row gap-4 md:gap-10 text-base md:text-sm lg:text-base text-serif text-white/50 justify-center text-center">
      <%= link_to 'Terms of Use', terms_path, class: "hover:underline" %>
      <%= link_to 'Privacy Policy', privacy_policy_path, class: "hover:underline" %>
      <a href="https://forms.gle/tXDb1uZ2Z4Q9yJJG8" target="_blank" class="hover:underline">お問い合せ</a>
    </div>
    <div class="mt-2 text-serif text-white/50 text-sm text-center">
      Copyright © 2025 - Empatia
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

	<div class="container mx-auto flex justify-end items-center px-4">
		<div class="flex gap-4 md:gap-8 text-serif text-white/50 text-base md:text-lg lg:text-xl">
			<%= link_to 'My Post', my_posts_path(current_user), class: 'hover:underline' %>
			<%= link_to 'Logout', logout_path, class: 'hover:underline', data: { turbo_method: :delete } %>
		</div>
	</div>
</header>