config/routes.rb
Rails.application.routes.draw do
  get "oauths/oauth"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get "oauths/callback"
  get "my_posts/index"
  root "static_pages#top"

  get "terms", to: "pages#terms"
  get "privacy_policy", to: "pages#privacy_policy"

  get "sign_up", to: "users#new"
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: [ :new, :create ]

  resources :my_posts, only: [ :index ]
  resources :my_likes, only: [ :index ]

  resources :posts do
    resources :likes, only: [ :create, :destroy ]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :content, invalid_words: true
  validates :content, presence: true, length: {maximum: 140}

  enum status: {published: 0, unpublished: 1}, _default: :published # 投稿のステータス(公開・非公開)

  scope :published, -> { where(status: :published) } # 公開の投稿だけを取得

  def self.ransackable_attributes(auth_object = nil)
    ["content"]
  end

  # いいねしているかどうかの判断
  def liked_by?(user, like_type)
    likes.any? { |like| like.user_id == user.id && like.like_type == like_type }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  before_action :ensure_correct_user, only: [ :edit, :update, :destroy ]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).eager_load(:user, :likes).published.where.not(user_id: current_user.id).order(created_at: :desc)
    @likes_by_post = Like.where(post_id: @posts.map(&:id)).group_by(&:post_id) # 投稿ごとの全いいね数を事前に取得
    @user_likes = Like.where(user_id: current_user.id, post_id: @posts.map(&:id)).group_by(&:post_id) # ユーザーがいいねしたデータを事前取得
    @message = @posts.empty? ? "検索結果はありませんでした" : nil
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = @post.published? ? "公開で投稿されました！" : "非公開で投稿されました！"
      redirect_to my_posts_path
    else
      flash[:alert] = "投稿に失敗しました。"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = current_user.posts.find_by(id: params[:id])
    if @post.nil?
      redirect_to my_posts_path, alert: "投稿が見つかりませんでした"
    end
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      if @post.saved_change_to_content?
        flash[:notice] = "投稿を編集しました"
      elsif @post.saved_change_to_status?
        flash[:notice] = @post.published? ? "公開に変更されました" : "非公開に変更されました"
      else
        flash[:notice] = "変更はありませんでした"
      end
      redirect_to my_posts_path
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy
      redirect_to my_posts_path, notice: "投稿が削除されました", status: :see_other
    end
  end

  private

  # 不正アクセスを防ぐ
  def ensure_correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      flash[:alert] = "権限がありません、不正アクセスです！"
      redirect_to posts_path
    end
  end

  def post_params
    params.require(:post).permit(:content, :status, :id)# postパラメーターの中から必要な属性を許可する
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_eighth_like.html.erb
<!---いいね8　　_like_buttonsにrenderさせる--->
<%= form_with url: post_likes_path(post), method: :post, data: { turbo_stream: true }, html: { id: "eighth-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_eighth' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-handshake text-blue-950"></i>
    <p class="text-xs" id="like-count-like_eighth-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_eighth' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_fifth_like.html.erb
<!---いいね5　　_like_buttonsにrenderさせる--->
<%= form_with url: post_likes_path(post), method: :post, data: { turbo_stream: true }, html: { id: "fifth-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_fifth' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-hand-fist text-blue-950"></i>
    <p class="text-xs" id="like-count-like_fifth-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_fifth' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_fifth_unlike.html.erb
<!--- いいね5  _like_buttonsにrenderさせる --->
<% like = @user_likes[post.id]&.find { |l| l.like_type == 'like_fifth' } %>

<%= form_with url: post_like_path(post, like), method: :delete, data: { turbo_stream: true }, html: { id: "like_fifth-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_fifth' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-hand-fist text-orange-200"></i>
    <p class="text-xs" id="like-count-like_fifth-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_fifth' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_first_like.html.erb
<!--- いいねを外した時のview _like_buttonsにrenderさせる --->
<%= form_with url: post_likes_path(post), method: :post, data: { turbo_stream: true }, html: { id: "first-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_first' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-heart text-blue-950"></i>
    <p class="text-xs" id="like-count-like_first-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_first' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_first_unlike.html.erb
<!--- いいねをした時のビュー　_like_buttonsにrenderさせる --->
<% like = @user_likes[post.id]&.find { |l| l.like_type == 'like_first' } %>

<%= form_with url: post_like_path(post, like), method: :delete, data: { turbo_stream: true }, html: { id: "like_first-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_first' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-heart text-pink-600"></i>
    <p class="text-xs" id="like-count-like_first-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_first' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_fourth_like.html.erb
<!---いいね4　　_like_buttonsにrenderさせる--->
<%= form_with url: post_likes_path(post), method: :post, data: { turbo_stream: true }, html: { id: "fourth-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_fourth' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-face-grin-squint text-blue-950"></i>
    <p class="text-xs" id="like-count-like_fourth-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_fourth' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_fourth_unlike.html.erb
<!--- いいね4  _like_buttonsにrenderさせる --->
<% like = @user_likes[post.id]&.find { |l| l.like_type == 'like_fourth' } %>

<%= form_with url: post_like_path(post, like), method: :delete, data: { turbo_stream: true }, html: { id: "like_fourth-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_fourth' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-face-grin-squint text-amber-300"></i>
    <p class="text-xs" id="like-count-like_fourth-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_fourth' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_post.html.erb
<!--- みんなの投稿 --->
<div class="w-96 p-4 border border-white/50 rounded-xl bg-white/60 backdrop-blur-md shadow-md">
  <div class="card-body">
    <p class="text-black text-lg"><%= post.content %></p>
    <p class="text-gray-500 text-sm mb-0.5"><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></p>
    <div class="mb-0">
      <%= render 'posts/like_buttons', post: post, likes: likes_by_post[post.id] %>
    </div>
  </div>
</div>

app/views/posts/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <div class="flex items-center space-x-2 border border-gray-300 rounded-lg px-3 py-2">
    <%= f.search_field :content_cont, class: "flex-grow outline-none bg-transparent" %>
    <button type="submit" class="text-white hover:text-gray-700">
      <i class="fa-solid fa-magnifying-glass text-lg"></i>
    </button>
  </div>
<% end %>

app/views/posts/_second_like.html.erb
<!--- _like_buttonsにrenderさせる --->
<%= form_with url: post_likes_path(post), method: :post, data: { turbo_stream: true }, html: { id: "second-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_second' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-heart-crack text-blue-950"></i>
    <p class="text-xs" id="like-count-like_second-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_second' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_second_unlike.html.erb
<!--- _like_buttonsにrenderさせる --->
<% like = @user_likes[post.id]&.find { |l| l.like_type == 'like_second' } %>

<%= form_with url: post_like_path(post, like), method: :delete, data: { turbo_stream: true }, html: { id: "like_second-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_second' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-heart-crack text-sky-600"></i>
    <p class="text-xs" id="like-count-like_second-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_second' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_third_like.html.erb
<!---いいね3　　_like_buttonsにrenderさせる--->
<%= form_with url: post_likes_path(post), method: :post, data: { turbo_stream: true }, html: { id: "third-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_third' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-face-angry text-blue-950"></i>
    <p class="text-xs" id="like-count-like_third-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_third' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/_third_unlike.html.erb
<!--- いいね3  _like_buttonsにrenderさせる --->
<% like = @user_likes[post.id]&.find { |l| l.like_type == 'like_third' } %>

<%= form_with url: post_like_path(post, like), method: :delete, data: { turbo_stream: true }, html: { id: "like_third-like-button-#{post.id}" } do %>
  <%= hidden_field_tag :like_type, 'like_third' %>
  <button type="submit" class="flex items-center space-x-1 text-gray-400 px-4 py-2">
    <i class="fa-solid fa-face-angry text-red-600"></i>
    <p class="text-xs" id="like-count-like_third-<%= post.id %>">
      <%= @likes_by_post[post.id]&.count { |l| l.like_type == 'like_third' } || 0 %>
    </p>
  </button>
<% end %>

app/views/posts/index.html.erb
<div class="relative w-full min-h-screen flex flex-col items-center py-16 bg-cover bg-center">
  <h2 class="text-center text-lg font-sans">検索欄</h2>
  <%= render 'search_form', q: @q, url: posts_path %>
  <p class="text-center text-black font-serif"><%= @message %></p>

<!--- ページ用のタブ --->
  <div class="flex justify-center">
    <div role="tablist" class="tabs tabs-bordered w-96 gap-2">
      <div role="tab" class="tab flex-1 text-center">
        <%= link_to 'みんなの投稿', posts_path %>
      </div>
      <div role="tab" class="tab flex-1 text-center">
        <%= link_to '自分の投稿', my_posts_path(current_user) %>
      </div>
      <div role="tab" class="tab flex-1 text-center">
        <%= link_to '共感一覧', my_likes_path(current_user) %>
      </div>
    </div>
  </div>

<!--- みんなの投稿を表示 --->
  <div class="flex justify-center">
    <div class="max-w-2xl w-full">
      <% if @posts.any? %>
        <%= render @posts, likes_by_post: @likes_by_post %>
      <% end %>
    </div>
  </div>
</div>